# Configuration options can be accessed as
# configatron.site_name

development: &local
    site_name: BaseApp
    site_namemobile: BaseApp Mobile
    site_url: baseapp.local
    
    company_name: BaseApp Ltd
    admin_email: admin@baseapp.local
    
    support_name: BaseApp Support
    support_email: support@baseapp.local
    
    site_envnote: Local Server

production:
    site_name: BaseApp
    site_namemobile: BaseApp Mobile
    site_url: www.baseapp.com
    
    company_name: BaseApp Ltd
    admin_email: admin@baseapp.com
    
    support_name: BaseApp Support
    support_email: support@baseapp.com
    
    site_envnote: Production Server
  
staging:
  <<: *local

test:
  <<: *local
